services:
  reboot.prices:
    image: reboot.prices
    build:
      context: .
      dockerfile: Reboot.Prices/Dockerfile

  reboot.api:
    image: reboot.api
    build:
      context: .
      dockerfile: Reboot.API/Dockerfile
