// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reboot.DB.Domain.Context;

#nullable disable

namespace Reboot.DB.Migrations
{
    [DbContext(typeof(RebootDatabaseContext))]
    [Migration("20240612150410_Added initial models")]
    partial class Addedinitialmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reboot.DB.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.OfferPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BudgetReplicaPrice")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("ReplicaPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("OfferId");

                    b.ToTable("OfferPrices");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneFabric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProducerCountry")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhoneFabrics");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("PhoneModels");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneModelModification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PhoneModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhoneModelId");

                    b.ToTable("PhoneModelModifications");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FabricId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FabricId");

                    b.ToTable("PhoneSeries");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.OfferPrice", b =>
                {
                    b.HasOne("Reboot.DB.Domain.Entities.PhoneModelModification", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reboot.DB.Domain.Entities.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneModel", b =>
                {
                    b.HasOne("Reboot.DB.Domain.Entities.PhoneSeries", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneModelModification", b =>
                {
                    b.HasOne("Reboot.DB.Domain.Entities.PhoneModel", "PhoneModel")
                        .WithMany()
                        .HasForeignKey("PhoneModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhoneModel");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneSeries", b =>
                {
                    b.HasOne("Reboot.DB.Domain.Entities.PhoneFabric", "Fabric")
                        .WithMany()
                        .HasForeignKey("FabricId");

                    b.Navigation("Fabric");
                });
#pragma warning restore 612, 618
        }
    }
}
