// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reboot.DB.Domain.Context;

#nullable disable

namespace Reboot.DB.Migrations
{
    [DbContext(typeof(RebootDatabaseContext))]
    [Migration("20240609164748_Added series db set")]
    partial class Addedseriesdbset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneFabric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProducerCountry")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhoneFabrics");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FabricId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FabricId");

                    b.ToTable("PhoneSeries");
                });

            modelBuilder.Entity("Reboot.DB.Domain.Entities.PhoneSeries", b =>
                {
                    b.HasOne("Reboot.DB.Domain.Entities.PhoneFabric", "Fabric")
                        .WithMany()
                        .HasForeignKey("FabricId");

                    b.Navigation("Fabric");
                });
#pragma warning restore 612, 618
        }
    }
}
